//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whydoisuck.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Whydoisuck.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why do I suck.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End percent.
        /// </summary>
        public static string AttemptListEndPercentHeader {
            get {
                return ResourceManager.GetString("AttemptListEndPercentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt {0}.
        /// </summary>
        public static string AttemptListNumberFormat {
            get {
                return ResourceManager.GetString("AttemptListNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string AttemptListNumberHeader {
            get {
                return ResourceManager.GetString("AttemptListNumberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F0}%.
        /// </summary>
        public static string AttemptListPercentFormat {
            get {
                return ResourceManager.GetString("AttemptListPercentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whydoisuck {0} by exyl.
        /// </summary>
        public static string AuthorFormat {
            get {
                return ResourceManager.GetString("AuthorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string CurrentLevelGroupDefault {
            get {
                return ResourceManager.GetString("CurrentLevelGroupDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder : .
        /// </summary>
        public static string CurrentLevelGroupLabel {
            get {
                return ResourceManager.GetString("CurrentLevelGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new folder.
        /// </summary>
        public static string CurrentLevelGroupNew {
            get {
                return ResourceManager.GetString("CurrentLevelGroupNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current session.
        /// </summary>
        public static string CurrentLevelNavButton {
            get {
                return ResourceManager.GetString("CurrentLevelNavButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting the level will save the session in a folder containing all sessions played on it, including copies. By clicking on the corresponding folder on the left, you can view statistics about the level..
        /// </summary>
        public static string CurrentLevelNotPlayingText {
            get {
                return ResourceManager.GetString("CurrentLevelNotPlayingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can start playing a level, every attempt spent on it is going to be registered !.
        /// </summary>
        public static string CurrentLevelNotPlayingTitle {
            get {
                return ResourceManager.GetString("CurrentLevelNotPlayingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not playing any level.
        /// </summary>
        public static string CurrentLevelTitleDefault {
            get {
                return ResourceManager.GetString("CurrentLevelTitleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd/MM/yyyy}.
        /// </summary>
        public static string DaySummaryHeaderFormat {
            get {
                return ResourceManager.GetString("DaySummaryHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete group.
        /// </summary>
        public static string DeleteGroupButtonText {
            get {
                return ResourceManager.GetString("DeleteGroupButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string DeleteGroupCaptionFormat {
            get {
                return ResourceManager.GetString("DeleteGroupCaptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the &quot;{0}&quot; folder ?.
        /// </summary>
        public static string DeleteGroupContentFormat {
            get {
                return ResourceManager.GetString("DeleteGroupContentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured, the application must stop. You may report this issue on the discord server..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about the error are logged in the folder: {0}.
        /// </summary>
        public static string ErrorMessageLogLocationFormat {
            get {
                return ResourceManager.GetString("ErrorMessageLogLocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show start position attempts.
        /// </summary>
        public static string FilterPanelCopyCheckbox {
            get {
                return ResourceManager.GetString("FilterPanelCopyCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show normal mode attempts.
        /// </summary>
        public static string FilterPanelNormalCheckbox {
            get {
                return ResourceManager.GetString("FilterPanelNormalCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest releases.
        /// </summary>
        public static string GithubLabel {
            get {
                return ResourceManager.GetString("GithubLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/exyl-exe/whydoisuck/releases.
        /// </summary>
        public static string GithubLink {
            get {
                return ResourceManager.GetString("GithubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass rate.
        /// </summary>
        public static string GraphPassRateAxisTitle {
            get {
                return ResourceManager.GetString("GraphPassRateAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level %.
        /// </summary>
        public static string GraphPercentAxisTitle {
            get {
                return ResourceManager.GetString("GraphPercentAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play time : {0:hh}h {0:mm}m {0:ss}s.
        /// </summary>
        public static string GraphPlayTimeFormat {
            get {
                return ResourceManager.GetString("GraphPlayTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current session.
        /// </summary>
        public static string GraphTitleCurrentSession {
            get {
                return ResourceManager.GetString("GraphTitleCurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session statistics.
        /// </summary>
        public static string GraphTitleIndividualSession {
            get {
                return ResourceManager.GetString("GraphTitleIndividualSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall statistics.
        /// </summary>
        public static string GraphTitleOverall {
            get {
                return ResourceManager.GetString("GraphTitleOverall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} attempts.
        /// </summary>
        public static string GraphTotalAttemptFormat {
            get {
                return ResourceManager.GetString("GraphTotalAttemptFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string SelectedLevelGraphTab {
            get {
                return ResourceManager.GetString("SelectedLevelGraphTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string SelectedLevelSessionsTab {
            get {
                return ResourceManager.GetString("SelectedLevelSessionsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SelectedLevelSettingsTab {
            get {
                return ResourceManager.GetString("SelectedLevelSettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} attempts.
        /// </summary>
        public static string SessionAttemptCountFormat {
            get {
                return ResourceManager.GetString("SessionAttemptCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} attempts.
        /// </summary>
        public static string SessionButtonCountFormat {
            get {
                return ResourceManager.GetString("SessionButtonCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from {0:0.##}%.
        /// </summary>
        public static string SessionButtonStartFormat {
            get {
                return ResourceManager.GetString("SessionButtonStartFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:hh}h{0:mm}.
        /// </summary>
        public static string SessionButtonTimeFormat {
            get {
                return ResourceManager.GetString("SessionButtonTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd/MM/yyyy} {0:HH}h{0:mm}.
        /// </summary>
        public static string SessionHeaderStartTimeFormat {
            get {
                return ResourceManager.GetString("SessionHeaderStartTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from {0:0.##}%.
        /// </summary>
        public static string SessionStartPercentFormat {
            get {
                return ResourceManager.GetString("SessionStartPercentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:hh}h{0:mm}.
        /// </summary>
        public static string SessionStartTimeFormat {
            get {
                return ResourceManager.GetString("SessionStartTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all attempts.
        /// </summary>
        public static string SessionViewShowAttempts {
            get {
                return ResourceManager.GetString("SessionViewShowAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show summary.
        /// </summary>
        public static string SessionViewShowStats {
            get {
                return ResourceManager.GetString("SessionViewShowStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death count.
        /// </summary>
        public static string StatsDeathColTitle {
            get {
                return ResourceManager.GetString("StatsDeathColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.##}%.
        /// </summary>
        public static string StatsItemPassRateFormat {
            get {
                return ResourceManager.GetString("StatsItemPassRateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass rate.
        /// </summary>
        public static string StatsPassRateColTitle {
            get {
                return ResourceManager.GetString("StatsPassRateColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string StatsPercentColTitle {
            get {
                return ResourceManager.GetString("StatsPercentColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reach count.
        /// </summary>
        public static string StatsReachColTitle {
            get {
                return ResourceManager.GetString("StatsReachColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Died {0} times.
        /// </summary>
        public static string TooltipDeathCountFormat {
            get {
                return ResourceManager.GetString("TooltipDeathCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.##}% pass rate.
        /// </summary>
        public static string TooltipPassRateFormat {
            get {
                return ResourceManager.GetString("TooltipPassRateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F0}%-{1:F0}%.
        /// </summary>
        public static string TooltipPercentFormat {
            get {
                return ResourceManager.GetString("TooltipPercentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reached {0} times.
        /// </summary>
        public static string TooltipReachCountFormat {
            get {
                return ResourceManager.GetString("TooltipReachCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
