//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whydoisuck.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Whydoisuck.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Why do i suck.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attempt {0}.
        /// </summary>
        public static string AttemptListNumberFormat {
            get {
                return ResourceManager.GetString("AttemptListNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:F0}%.
        /// </summary>
        public static string AttemptListPercentFormat {
            get {
                return ResourceManager.GetString("AttemptListPercentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à none.
        /// </summary>
        public static string CurrentLevelGroupDefault {
            get {
                return ResourceManager.GetString("CurrentLevelGroupDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Level group : .
        /// </summary>
        public static string CurrentLevelGroupLabel {
            get {
                return ResourceManager.GetString("CurrentLevelGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à new group.
        /// </summary>
        public static string CurrentLevelGroupNew {
            get {
                return ResourceManager.GetString("CurrentLevelGroupNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current session.
        /// </summary>
        public static string CurrentLevelNavButton {
            get {
                return ResourceManager.GetString("CurrentLevelNavButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not playing any level.
        /// </summary>
        public static string CurrentLevelTitleDefault {
            get {
                return ResourceManager.GetString("CurrentLevelTitleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:dd/MM/yyyy}.
        /// </summary>
        public static string DaySummaryHeaderFormat {
            get {
                return ResourceManager.GetString("DaySummaryHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show start position attempts.
        /// </summary>
        public static string FilterPanelCopyCheckbox {
            get {
                return ResourceManager.GetString("FilterPanelCopyCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show normal mode attempts.
        /// </summary>
        public static string FilterPanelNormalCheckbox {
            get {
                return ResourceManager.GetString("FilterPanelNormalCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pass rate.
        /// </summary>
        public static string GraphPassRateAxisTitle {
            get {
                return ResourceManager.GetString("GraphPassRateAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Level %.
        /// </summary>
        public static string GraphPercentAxisTitle {
            get {
                return ResourceManager.GetString("GraphPercentAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current session.
        /// </summary>
        public static string GraphTitleCurrentSession {
            get {
                return ResourceManager.GetString("GraphTitleCurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statistics.
        /// </summary>
        public static string SelectedLevelGraphTab {
            get {
                return ResourceManager.GetString("SelectedLevelGraphTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sessions.
        /// </summary>
        public static string SelectedLevelSessionsTab {
            get {
                return ResourceManager.GetString("SelectedLevelSessionsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} attempts.
        /// </summary>
        public static string SessionAttemptCountFormat {
            get {
                return ResourceManager.GetString("SessionAttemptCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à from {0:0.##}%.
        /// </summary>
        public static string SessionStartPercentFormat {
            get {
                return ResourceManager.GetString("SessionStartPercentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:hh}h{0:mm}.
        /// </summary>
        public static string SessionStartTimeFormat {
            get {
                return ResourceManager.GetString("SessionStartTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show all attempts.
        /// </summary>
        public static string SessionViewShowAttempts {
            get {
                return ResourceManager.GetString("SessionViewShowAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show summary.
        /// </summary>
        public static string SessionViewShowStats {
            get {
                return ResourceManager.GetString("SessionViewShowStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Death count.
        /// </summary>
        public static string StatsDeathColTitle {
            get {
                return ResourceManager.GetString("StatsDeathColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pass rate.
        /// </summary>
        public static string StatsPassRateColTitle {
            get {
                return ResourceManager.GetString("StatsPassRateColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Percent.
        /// </summary>
        public static string StatsPercentColTitle {
            get {
                return ResourceManager.GetString("StatsPercentColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reach count.
        /// </summary>
        public static string StatsReachColTitle {
            get {
                return ResourceManager.GetString("StatsReachColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Died {0} times.
        /// </summary>
        public static string TooltipDeathCountFormat {
            get {
                return ResourceManager.GetString("TooltipDeathCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:F0}% pass rate.
        /// </summary>
        public static string TooltipPassRateFormat {
            get {
                return ResourceManager.GetString("TooltipPassRateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:F0}%-{1:F0}%.
        /// </summary>
        public static string TooltipPercentFormat {
            get {
                return ResourceManager.GetString("TooltipPercentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reached {0} times.
        /// </summary>
        public static string TooltipReachCountFormat {
            get {
                return ResourceManager.GetString("TooltipReachCountFormat", resourceCulture);
            }
        }
    }
}
