//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ydis.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ydis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ydis.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End percent.
        /// </summary>
        public static string AttemptListEndPercentHeader {
            get {
                return ResourceManager.GetString("AttemptListEndPercentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attempt {0}.
        /// </summary>
        public static string AttemptListNumberFormat {
            get {
                return ResourceManager.GetString("AttemptListNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number.
        /// </summary>
        public static string AttemptListNumberHeader {
            get {
                return ResourceManager.GetString("AttemptListNumberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:F0}%.
        /// </summary>
        public static string AttemptListPercentFormat {
            get {
                return ResourceManager.GetString("AttemptListPercentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run length.
        /// </summary>
        public static string AttemptListRunLengthHeader {
            get {
                return ResourceManager.GetString("AttemptListRunLengthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start percent.
        /// </summary>
        public static string AttemptListStartPercentHeader {
            get {
                return ResourceManager.GetString("AttemptListStartPercentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ydis {0} by exyl.
        /// </summary>
        public static string AuthorFormat {
            get {
                return ResourceManager.GetString("AuthorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à none.
        /// </summary>
        public static string CurrentLevelGroupDefault {
            get {
                return ResourceManager.GetString("CurrentLevelGroupDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Folder : .
        /// </summary>
        public static string CurrentLevelGroupLabel {
            get {
                return ResourceManager.GetString("CurrentLevelGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à new folder.
        /// </summary>
        public static string CurrentLevelGroupNew {
            get {
                return ResourceManager.GetString("CurrentLevelGroupNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current session.
        /// </summary>
        public static string CurrentLevelNavButton {
            get {
                return ResourceManager.GetString("CurrentLevelNavButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exiting the level will save the session in a folder containing all sessions played on it, including copies. By clicking on the corresponding folder on the left, you can view statistics about the level..
        /// </summary>
        public static string CurrentLevelNotPlayingText {
            get {
                return ResourceManager.GetString("CurrentLevelNotPlayingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thanks for using Ydis, your attempts are now going to be registered !.
        /// </summary>
        public static string CurrentLevelNotPlayingTitle {
            get {
                return ResourceManager.GetString("CurrentLevelNotPlayingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not playing any level.
        /// </summary>
        public static string CurrentLevelTitleDefault {
            get {
                return ResourceManager.GetString("CurrentLevelTitleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:dd/MM/yyyy}.
        /// </summary>
        public static string DaySummaryHeaderFormat {
            get {
                return ResourceManager.GetString("DaySummaryHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete folder.
        /// </summary>
        public static string DeleteGroupButtonText {
            get {
                return ResourceManager.GetString("DeleteGroupButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete {0}.
        /// </summary>
        public static string DeleteGroupCaptionFormat {
            get {
                return ResourceManager.GetString("DeleteGroupCaptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete the &quot;{0}&quot; folder ?.
        /// </summary>
        public static string DeleteGroupContentFormat {
            get {
                return ResourceManager.GetString("DeleteGroupContentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suggest features and report issues.
        /// </summary>
        public static string DiscordLabel {
            get {
                return ResourceManager.GetString("DiscordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://discord.gg/fgYUcqd4Mk.
        /// </summary>
        public static string DiscordLink {
            get {
                return ResourceManager.GetString("DiscordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured, the application must stop. You may report this issue on the discord server..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information about the error are logged in the folder: {0}.
        /// </summary>
        public static string ErrorMessageLogLocationFormat {
            get {
                return ResourceManager.GetString("ErrorMessageLogLocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show start position attempts.
        /// </summary>
        public static string FilterPanelCopyCheckbox {
            get {
                return ResourceManager.GetString("FilterPanelCopyCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show normal mode attempts.
        /// </summary>
        public static string FilterPanelNormalCheckbox {
            get {
                return ResourceManager.GetString("FilterPanelNormalCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show practice mode attempts.
        /// </summary>
        public static string FilterPanelPracticeCheckbox {
            get {
                return ResourceManager.GetString("FilterPanelPracticeCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete selected folders.
        /// </summary>
        public static string FolderManagementDeleteButton {
            get {
                return ResourceManager.GetString("FolderManagementDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merge selected folders.
        /// </summary>
        public static string FolderManagementMergeButton {
            get {
                return ResourceManager.GetString("FolderManagementMergeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reorganize all folders.
        /// </summary>
        public static string FolderManagementReorganizeAllButton {
            get {
                return ResourceManager.GetString("FolderManagementReorganizeAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reorganize selected folders.
        /// </summary>
        public static string FolderManagementReorganizeButton {
            get {
                return ResourceManager.GetString("FolderManagementReorganizeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Folder management.
        /// </summary>
        public static string FolderManagementTitle {
            get {
                return ResourceManager.GetString("FolderManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Latest releases.
        /// </summary>
        public static string GithubLabel {
            get {
                return ResourceManager.GetString("GithubLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://github.com/exyl-exe/ydis/releases.
        /// </summary>
        public static string GithubLink {
            get {
                return ResourceManager.GetString("GithubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pass rate.
        /// </summary>
        public static string GraphPassRateAxisTitle {
            get {
                return ResourceManager.GetString("GraphPassRateAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Level %.
        /// </summary>
        public static string GraphPercentAxisTitle {
            get {
                return ResourceManager.GetString("GraphPercentAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play time : {1:D2}h {0:mm}m {0:ss}s.
        /// </summary>
        public static string GraphPlayTimeFormat {
            get {
                return ResourceManager.GetString("GraphPlayTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current session.
        /// </summary>
        public static string GraphTitleCurrentSession {
            get {
                return ResourceManager.GetString("GraphTitleCurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Session statistics.
        /// </summary>
        public static string GraphTitleIndividualSession {
            get {
                return ResourceManager.GetString("GraphTitleIndividualSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Overall statistics.
        /// </summary>
        public static string GraphTitleOverall {
            get {
                return ResourceManager.GetString("GraphTitleOverall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} attempts.
        /// </summary>
        public static string GraphTotalAttemptFormat {
            get {
                return ResourceManager.GetString("GraphTotalAttemptFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage folders.
        /// </summary>
        public static string ManageFoldersButton {
            get {
                return ResourceManager.GetString("ManageFoldersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete {0} folders.
        /// </summary>
        public static string ManagementDeleteFoldersCaptionFormat {
            get {
                return ResourceManager.GetString("ManagementDeleteFoldersCaptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to delete the {0} selected folders ? This is irreversible..
        /// </summary>
        public static string ManagementDeleteFoldersContentFormat {
            get {
                return ResourceManager.GetString("ManagementDeleteFoldersContentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merge {0} groups.
        /// </summary>
        public static string ManagementMergeFoldersCaptionFormat {
            get {
                return ResourceManager.GetString("ManagementMergeFoldersCaptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to merge the {0} selected folders into one folder ? All of their data will be stored in the &quot;{1}&quot; folder..
        /// </summary>
        public static string ManagementMergeFoldersContentFormat {
            get {
                return ResourceManager.GetString("ManagementMergeFoldersContentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reorganize all folders.
        /// </summary>
        public static string ManagementReorganizeAllCaption {
            get {
                return ResourceManager.GetString("ManagementReorganizeAllCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want ALL of your data to be reorganized ? This will put every session in their default folder. This can be used in case your data was messed up by merging operations..
        /// </summary>
        public static string ManagementReorganizeAllContent {
            get {
                return ResourceManager.GetString("ManagementReorganizeAllContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reorganize {0} selected folders.
        /// </summary>
        public static string ManagementReorganizeSelectedCaptionFormat {
            get {
                return ResourceManager.GetString("ManagementReorganizeSelectedCaptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to reorganize the {0} selected folders ? Their data will be reorganized using the default criteria. This is useful to undo merging operations..
        /// </summary>
        public static string ManagementReorganizeSelectedContentFormat {
            get {
                return ResourceManager.GetString("ManagementReorganizeSelectedContentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move existing data.
        /// </summary>
        public static string MigrateDataCaption {
            get {
                return ResourceManager.GetString("MigrateDataCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to move current data ? It will be merged with the save files at the given location :
        ///{0}.
        /// </summary>
        public static string MigrateDataContentFormat {
            get {
                return ResourceManager.GetString("MigrateDataContentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statistics.
        /// </summary>
        public static string SelectedLevelGraphTab {
            get {
                return ResourceManager.GetString("SelectedLevelGraphTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sessions.
        /// </summary>
        public static string SelectedLevelSessionsTab {
            get {
                return ResourceManager.GetString("SelectedLevelSessionsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Folder settings.
        /// </summary>
        public static string SelectedLevelSettingsTab {
            get {
                return ResourceManager.GetString("SelectedLevelSettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} attempts.
        /// </summary>
        public static string SessionAttemptCountFormat {
            get {
                return ResourceManager.GetString("SessionAttemptCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} attempts.
        /// </summary>
        public static string SessionButtonCountFormat {
            get {
                return ResourceManager.GetString("SessionButtonCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à from {0:0.##}%.
        /// </summary>
        public static string SessionButtonStartFormat {
            get {
                return ResourceManager.GetString("SessionButtonStartFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:hh}h{0:mm}.
        /// </summary>
        public static string SessionButtonTimeFormat {
            get {
                return ResourceManager.GetString("SessionButtonTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:dd/MM/yyyy} {0:HH}h{0:mm}.
        /// </summary>
        public static string SessionHeaderStartTimeFormat {
            get {
                return ResourceManager.GetString("SessionHeaderStartTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à from {0:0.##}%.
        /// </summary>
        public static string SessionStartPercentFormat {
            get {
                return ResourceManager.GetString("SessionStartPercentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:hh}h{0:mm}.
        /// </summary>
        public static string SessionStartTimeFormat {
            get {
                return ResourceManager.GetString("SessionStartTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show all attempts.
        /// </summary>
        public static string SessionViewShowAttempts {
            get {
                return ResourceManager.GetString("SessionViewShowAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show summary.
        /// </summary>
        public static string SessionViewShowStats {
            get {
                return ResourceManager.GetString("SessionViewShowStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import existing data.
        /// </summary>
        public static string SettingsImportData {
            get {
                return ResourceManager.GetString("SettingsImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import data stored in a different folder..
        /// </summary>
        public static string SettingsImportDataDesc {
            get {
                return ResourceManager.GetString("SettingsImportDataDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move current save files ?.
        /// </summary>
        public static string SettingsMoveDataCaption {
            get {
                return ResourceManager.GetString("SettingsMoveDataCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to move the current save files to the new location ? If there already are save files at the given location, they will be merged with the current save files..
        /// </summary>
        public static string SettingsMoveDataContent {
            get {
                return ResourceManager.GetString("SettingsMoveDataContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automatically start when Geometry Dash is launched.
        /// </summary>
        public static string SettingsOnStart {
            get {
                return ResourceManager.GetString("SettingsOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ydis will be automatically opened when Geometry Dash launched.
        ///This requires a very light process to run as a background task..
        /// </summary>
        public static string SettingsOnStartDesc {
            get {
                return ResourceManager.GetString("SettingsOnStartDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Privilege accuracy over performance.
        /// </summary>
        public static string SettingsPerformanceMode {
            get {
                return ResourceManager.GetString("SettingsPerformanceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enhances accuracy but consumes (slightly) more CPU..
        /// </summary>
        public static string SettingsPerformanceModeDesc {
            get {
                return ResourceManager.GetString("SettingsPerformanceModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change save files location.
        /// </summary>
        public static string SettingsSaveLocation {
            get {
                return ResourceManager.GetString("SettingsSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Controls how much time there is between two consecutive scans of the game&apos;s memory. A longer delay means better performance at the cost of accuracy in some edge cases..
        /// </summary>
        public static string SettingsScanRateDesc {
            get {
                return ResourceManager.GetString("SettingsScanRateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Death count.
        /// </summary>
        public static string StatsDeathColTitle {
            get {
                return ResourceManager.GetString("StatsDeathColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:0.##}%.
        /// </summary>
        public static string StatsItemPassRateFormat {
            get {
                return ResourceManager.GetString("StatsItemPassRateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pass rate.
        /// </summary>
        public static string StatsPassRateColTitle {
            get {
                return ResourceManager.GetString("StatsPassRateColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Percent.
        /// </summary>
        public static string StatsPercentColTitle {
            get {
                return ResourceManager.GetString("StatsPercentColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reach count.
        /// </summary>
        public static string StatsReachColTitle {
            get {
                return ResourceManager.GetString("StatsReachColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Died {0} times.
        /// </summary>
        public static string TooltipDeathCountFormat {
            get {
                return ResourceManager.GetString("TooltipDeathCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:0.##}% pass rate.
        /// </summary>
        public static string TooltipPassRateFormat {
            get {
                return ResourceManager.GetString("TooltipPassRateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:F0}%-{1:F0}%.
        /// </summary>
        public static string TooltipPercentFormat {
            get {
                return ResourceManager.GetString("TooltipPercentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reached {0} times.
        /// </summary>
        public static string TooltipReachCountFormat {
            get {
                return ResourceManager.GetString("TooltipReachCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1.1.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
